void trasmitNec(unsigned int adress, unsigned int command)
void transmitSamsung(unsigned int adress, unsigned int command)
void transmitRC5(unsigned int adress, unsigned int command)
void transmitRC6(unsigned int adress, unsigned int command)
void transmitSIRC(unsigned int adress, unsigned int command, int bit_mode)